### PR TITLE
Don't crash on disconnect

### PR DESCRIPTION
**Pull request by timhuff**

### CODE REVIEW

**Comment by HaroldoTeruya** [comment]
@renanpupin

**Comment by JWalker1995** [comment]
I can confirm this prevents android from crashing when `cleanUpPublisher` is called from `onStreamDestroyed`

**Comment by jukben** [comment]
Thanks for the PR. Is that somehow related to #89? @JWalker1995 @timhuff @HaroldoTeruya

**Comment by timhuff** [comment]
I'm not sure. They seem to both be the result of resource management going wrong at some point. Wish I could remember because I recall thinking I had a decent idea of what was happening... oh! My guess was that OpenTok's new SDK starting releasing the resource and then on disconnect, you would, too. Like double freeing a pointer. I think I concluded that it was ultimately TokBox's fault. I can tell you, though, that this fix has been deployed to thousands of users without complaint for about 2 months now.

**Comment by timhuff** [comment]
Looks like the repo has implemented an equivalent change since this pull request was created.

**Pull request closed without merging**
